/*
 * fenPrincipale.java
 *
 * Created on 24 octobre 2008, 10:27
 */

package test;

/**
 *
 * @author  slefort
 */
public class fenPrincipale extends javax.swing.JFrame {

    /** Creates new form fenPrincipale */
    public fenPrincipale() {
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPanelQcm = new javax.swing.JTabbedPane();
        PanelTest = new javax.swing.JPanel();
        labelListeTest = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListTests = new javax.swing.JList();
        jPanelProprietesTest = new javax.swing.JPanel();
        jLabelNomTest = new javax.swing.JLabel();
        jLabelTempsTest = new javax.swing.JLabel();
        jLabelSeuilTest = new javax.swing.JLabel();
        jTextFieldNomTest = new javax.swing.JTextField();
        jTextFieldTempsTest = new javax.swing.JTextField();
        jTextFieldSeuilTest = new javax.swing.JTextField();
        PanelSection = new javax.swing.JPanel();
        PanelQuestion = new javax.swing.JPanel();
        MenuQcm = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelListeTest.setText("Liste des tests :");

        jListTests.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Test 1", "Tests 2"};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListTests);

        jPanelProprietesTest.setBorder(javax.swing.BorderFactory.createTitledBorder("Propriétés"));

        jLabelNomTest.setText("Nom :");

        jLabelTempsTest.setText("Temps :");

        jLabelSeuilTest.setText("Seuil :");

        javax.swing.GroupLayout jPanelProprietesTestLayout = new javax.swing.GroupLayout(jPanelProprietesTest);
        jPanelProprietesTest.setLayout(jPanelProprietesTestLayout);
        jPanelProprietesTestLayout.setHorizontalGroup(
            jPanelProprietesTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProprietesTestLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelProprietesTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelProprietesTestLayout.createSequentialGroup()
                        .addComponent(jLabelNomTest)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNomTest, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelProprietesTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelProprietesTestLayout.createSequentialGroup()
                            .addComponent(jLabelSeuilTest)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldSeuilTest))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelProprietesTestLayout.createSequentialGroup()
                            .addComponent(jLabelTempsTest)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldTempsTest, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanelProprietesTestLayout.setVerticalGroup(
            jPanelProprietesTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProprietesTestLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProprietesTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomTest)
                    .addComponent(jTextFieldNomTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelProprietesTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTempsTest)
                    .addComponent(jTextFieldTempsTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelProprietesTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSeuilTest)
                    .addComponent(jTextFieldSeuilTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelTestLayout = new javax.swing.GroupLayout(PanelTest);
        PanelTest.setLayout(PanelTestLayout);
        PanelTestLayout.setHorizontalGroup(
            PanelTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTestLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTestLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jPanelProprietesTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelListeTest))
                .addContainerGap(262, Short.MAX_VALUE))
        );
        PanelTestLayout.setVerticalGroup(
            PanelTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTestLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelListeTest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelProprietesTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(236, Short.MAX_VALUE))
        );

        jTabbedPanelQcm.addTab("Tests", PanelTest);

        javax.swing.GroupLayout PanelSectionLayout = new javax.swing.GroupLayout(PanelSection);
        PanelSection.setLayout(PanelSectionLayout);
        PanelSectionLayout.setHorizontalGroup(
            PanelSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 742, Short.MAX_VALUE)
        );
        PanelSectionLayout.setVerticalGroup(
            PanelSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );

        jTabbedPanelQcm.addTab("Sections", PanelSection);

        javax.swing.GroupLayout PanelQuestionLayout = new javax.swing.GroupLayout(PanelQuestion);
        PanelQuestion.setLayout(PanelQuestionLayout);
        PanelQuestionLayout.setHorizontalGroup(
            PanelQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 742, Short.MAX_VALUE)
        );
        PanelQuestionLayout.setVerticalGroup(
            PanelQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );

        jTabbedPanelQcm.addTab("Questions", PanelQuestion);

        jMenu1.setText("Menu");
        MenuQcm.add(jMenu1);

        jMenu2.setText("Options");
        MenuQcm.add(jMenu2);

        setJMenuBar(MenuQcm);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPanelQcm, javax.swing.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPanelQcm, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fenPrincipale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuQcm;
    private javax.swing.JPanel PanelQuestion;
    private javax.swing.JPanel PanelSection;
    private javax.swing.JPanel PanelTest;
    private javax.swing.JLabel jLabelNomTest;
    private javax.swing.JLabel jLabelSeuilTest;
    private javax.swing.JLabel jLabelTempsTest;
    private javax.swing.JList jListTests;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanelProprietesTest;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPanelQcm;
    private javax.swing.JTextField jTextFieldNomTest;
    private javax.swing.JTextField jTextFieldSeuilTest;
    private javax.swing.JTextField jTextFieldTempsTest;
    private javax.swing.JLabel labelListeTest;
    // End of variables declaration//GEN-END:variables

}
